# permissions for end users to view loggerdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loggerdemo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: logger-operator
    app.kubernetes.io/part-of: logger-operator
    app.kubernetes.io/managed-by: kustomize
  name: loggerdemo-viewer-role
rules:
- apiGroups:
  - github.github.com
  resources:
  - loggerdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.github.com
  resources:
  - loggerdemoes/status
  verbs:
  - get
