---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github.github.com
  resources:
  - loggerdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.github.com
  resources:
  - loggerdemoes/finalizers
  verbs:
  - update
- apiGroups:
  - github.github.com
  resources:
  - loggerdemoes/status
  verbs:
  - get
  - patch
  - update
